### PR TITLE
Add test check fields

### PR DESCRIPTION
**Pull request by sauve**
Implemented basic unit tests for the check_fields methods. The four types of analysis are tested ( occurrence_core/default, event_code, occurrence_extension and extended_measurement_or_fact_extension ).

### CODE REVIEW

**Comment by jdpye** [comment]
looks like the CI needs some configuration repair.

**Comment by sauve** [comment]
Github CI is really not my expertise. Anybody available to try to fix that? Same problem with all PRs.

**Comment by kwilcox** [comment]
The error message says to do what we are already doing.... I can take a look.

`throw Error("Must provide 'environment-name' for 'environment-file: false'")`

We have that... https://github.com/cioos-siooc/pyobistools/blob/main/.github/workflows/default-tests.yml#L19-L22

**Comment by kwilcox** [comment]
I pushed changes into `main` that fix CI, you'll have to rebase on top of main to pick them up... then this will pass.

**Pull request merged**
