### PR TITLE
update environment.yml to remove pip-by-urls

### PR DESCRIPTION
**Pull request by jdpye**
Attempting to remove some of the weird dependencies now that pyxylookup is published in PyPI. Will hopefully be able to remove obis-qc and isodateparser as direct dependencies.

### CODE REVIEW

**Comment by BeauvillierS** [comment]
> Looks like it didn't complain. Not sure if we ever leverage isodateparser or obis-qc directly anywhere, a text scan says we no longer rely on them so we can probably get by without them in the dependencies.

I see that too. obis-qc is only refered in 'check_onland'

**Comment by BeauvillierS** [comment]
just installed the latest pyobistools (at latest commit 39a92dec4fd328229cd0baf4958232f1959aaa9c) and tried to run check_onland in a notebook... seems like pyxylookup was not installed... is it because it is not registered? @jdpye

**Comment by jdpye** [comment]
pyxylookup is now in setup.cfg as a dependency, adding cartopy made pip very angry on Ubuntu Linux. Trying other ways now as well.

**Comment by jdpye** [comment]
Got cartopy to install happily on windows and on the test suite. I think we made it!

**Pull request merged**
