### PR TITLE
bunch of modifications

### PR DESCRIPTION
**Pull request by BeauvillierS**
in summary:
- created static csv files for the notebooks
- changed how the results are displayed for the check_scientificname_and_ids function
- modified the environment file to add two packages

### CODE REVIEW

**Comment by BeauvillierS** [comment]
looks good to merge all this!

**Comment by BeauvillierS** [comment]
@jdpye can you help with the pre-commit? can't find where it's failing

**Comment by jdpye** [comment]
Looks like one of our dependencies in the github actions was deprecated recently. looking at what to fix in order to bring back our auto-checking. we can skip over pre-commit for the moment while I do that.

**Comment by jdpye** [comment]
Fixes look to be either going to Python 3.9+ or pinning `importlib-metadata` to < 5.0 in our setup.

**Pull request merged**
